model: yolov8m.pt
data: settings.yaml
epochs: 100
batch: 2
imgsz: 640
patience: 20
workers: 2
amp: true
device: 0

optimizer: SGD           
lr0: 0.01
lrf: 0.1             
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
cos_lr: true

box: 7.5
cls: 0.5       
dfl: 1.5

degrees: 0.0
shear: 0.0
perspective: 0.0
translate: 0.1
scale: 0.5             
fliplr: 0.5
mosaic: 0.6
close_mosaic: 10
mixup: 0.1
copy_paste: 0.3
hsv_h: 0.015
hsv_s: 0.6
hsv_v: 0.5

rect: false
seed: 42
